### ISSUE TITLE
`No such file or directory, open '...'` on every command

### ISSUE THREAD

**Issue by INF-INITY** [CRBT-Team/Purplet#1]
Full error:
```
[ Error ] ENOENT: no such file or directory, open 'mnt/Data/.../interaction.ts'
    at Object.openSync (node.js)
    at Object.readFileSync (node.js)
    at getModuleName (purplet)
    at file:///mnt/Data/CRBT/node_modules/purplet/dist/index.mjs:879:34
    at String.replace (<anonymous>)
    at file:///mnt/Data/CRBT/node_modules/purplet/dist/index.mjs:853:21
    at Array.map (<anonymous>)
    at cleanStackTraces (purplet)
    at process.handleError (purplet)
```

This file 100% exists however it throws this error after every command. I think this is because if you look where the path is, there's no `/` before it. Maybe it's running from a different folder and trying to find `mnt` within it? This error only seems to happen on Linux.

**Comment by INF-INITY** [comment]
nevermind clembs has the big dumb
